[package]
name = "trazodone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hvm = "1.0.6"
libc = "0.2.139"
llvm-sys = "150.0.5"
